name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
              sudo update-alternatives --display gcc
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 80
              sudo update-alternatives --set gcc /usr/bin/gcc-9
              sudo update-alternatives --set cc /usr/bin/gcc
              make

